# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f302a9a23e5b6f7782decb4f05e8fafafa6acf01d947977e09a5b8fbc271ff316f5a7bb93804c17227c957412688675472635b91de97912bad0fdc4a062d04

test:
  secret_key_base: 9a68373d95823a15f1b770e43cd0a8c821e0a0b80101fe5adb7fdd66a03d7484552e3b392f32b5574521160aafe6f0857649e98aaf50cc2a147d49e16350588c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
